version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - sqlitedata:/app/sqlitedata
    env_file:
      - .env
    restart: always

volumes:
  sqlitedata:
